// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/stats_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/stats_service.go -destination=internal/service/mock/stats_service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	models "github.com/mrhumster/stats-service/internal/domain/models"
	service "github.com/mrhumster/stats-service/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockStatsService is a mock of StatsService interface.
type MockStatsService struct {
	ctrl     *gomock.Controller
	recorder *MockStatsServiceMockRecorder
	isgomock struct{}
}

// MockStatsServiceMockRecorder is the mock recorder for MockStatsService.
type MockStatsServiceMockRecorder struct {
	mock *MockStatsService
}

// NewMockStatsService creates a new mock instance.
func NewMockStatsService(ctrl *gomock.Controller) *MockStatsService {
	mock := &MockStatsService{ctrl: ctrl}
	mock.recorder = &MockStatsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsService) EXPECT() *MockStatsServiceMockRecorder {
	return m.recorder
}

// GetStats mocks base method.
func (m *MockStatsService) GetStats(ctx context.Context, streamID uuid.UUID, actor *service.Actor) (*models.Stats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx, streamID, actor)
	ret0, _ := ret[0].(*models.Stats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockStatsServiceMockRecorder) GetStats(ctx, streamID, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockStatsService)(nil).GetStats), ctx, streamID, actor)
}

// RegisterView mocks base method.
func (m *MockStatsService) RegisterView(ctx context.Context, streamID uuid.UUID, viewerKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterView", ctx, streamID, viewerKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterView indicates an expected call of RegisterView.
func (mr *MockStatsServiceMockRecorder) RegisterView(ctx, streamID, viewerKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterView", reflect.TypeOf((*MockStatsService)(nil).RegisterView), ctx, streamID, viewerKey)
}

// SetReaction mocks base method.
func (m *MockStatsService) SetReaction(ctx context.Context, actor service.Actor, streamID uuid.UUID, kind models.ReactionKind) (*models.Stats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetReaction", ctx, actor, streamID, kind)
	ret0, _ := ret[0].(*models.Stats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetReaction indicates an expected call of SetReaction.
func (mr *MockStatsServiceMockRecorder) SetReaction(ctx, actor, streamID, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReaction", reflect.TypeOf((*MockStatsService)(nil).SetReaction), ctx, actor, streamID, kind)
}
