// Code generated by MockGen. DO NOT EDIT.
// Source: internal/stream/status_client.go
//
// Generated by this command:
//
//	mockgen -source=internal/stream/status_client.go -destination=internal/stream/mock/status_client_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	stream "github.com/mrhumster/stats-service/internal/stream"
	gomock "go.uber.org/mock/gomock"
)

// MockStatusClient is a mock of StatusClient interface.
type MockStatusClient struct {
	ctrl     *gomock.Controller
	recorder *MockStatusClientMockRecorder
	isgomock struct{}
}

// MockStatusClientMockRecorder is the mock recorder for MockStatusClient.
type MockStatusClientMockRecorder struct {
	mock *MockStatusClient
}

// NewMockStatusClient creates a new mock instance.
func NewMockStatusClient(ctrl *gomock.Controller) *MockStatusClient {
	mock := &MockStatusClient{ctrl: ctrl}
	mock.recorder = &MockStatusClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusClient) EXPECT() *MockStatusClientMockRecorder {
	return m.recorder
}

// GetStreamStatus mocks base method.
func (m *MockStatusClient) GetStreamStatus(ctx context.Context, streamID uuid.UUID) (*stream.StatusInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStreamStatus", ctx, streamID)
	ret0, _ := ret[0].(*stream.StatusInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStreamStatus indicates an expected call of GetStreamStatus.
func (mr *MockStatusClientMockRecorder) GetStreamStatus(ctx, streamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStreamStatus", reflect.TypeOf((*MockStatusClient)(nil).GetStreamStatus), ctx, streamID)
}
