// Code generated by MockGen. DO NOT EDIT.
// Source: internal/viewer/deduper.go
//
// Generated by this command:
//
//	mockgen -source=internal/viewer/deduper.go -destination=internal/viewer/mock/viewer_deduper_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDeduper is a mock of Deduper interface.
type MockDeduper struct {
	ctrl     *gomock.Controller
	recorder *MockDeduperMockRecorder
	isgomock struct{}
}

// MockDeduperMockRecorder is the mock recorder for MockDeduper.
type MockDeduperMockRecorder struct {
	mock *MockDeduper
}

// NewMockDeduper creates a new mock instance.
func NewMockDeduper(ctrl *gomock.Controller) *MockDeduper {
	mock := &MockDeduper{ctrl: ctrl}
	mock.recorder = &MockDeduperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeduper) EXPECT() *MockDeduperMockRecorder {
	return m.recorder
}

// Allow mocks base method.
func (m *MockDeduper) Allow(ctx context.Context, streamID uuid.UUID, viewerKey string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allow", ctx, streamID, viewerKey)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Allow indicates an expected call of Allow.
func (mr *MockDeduperMockRecorder) Allow(ctx, streamID, viewerKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allow", reflect.TypeOf((*MockDeduper)(nil).Allow), ctx, streamID, viewerKey)
}

// Close mocks base method.
func (m *MockDeduper) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDeduperMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDeduper)(nil).Close))
}
