// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/stats_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/stats_repository.go -destination=internal/repository/mock/stats_repository_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	models "github.com/mrhumster/stats-service/internal/domain/models"
	gomock "go.uber.org/mock/gomock"
)

// MockStatsRepository is a mock of StatsRepository interface.
type MockStatsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStatsRepositoryMockRecorder
	isgomock struct{}
}

// MockStatsRepositoryMockRecorder is the mock recorder for MockStatsRepository.
type MockStatsRepositoryMockRecorder struct {
	mock *MockStatsRepository
}

// NewMockStatsRepository creates a new mock instance.
func NewMockStatsRepository(ctrl *gomock.Controller) *MockStatsRepository {
	mock := &MockStatsRepository{ctrl: ctrl}
	mock.recorder = &MockStatsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsRepository) EXPECT() *MockStatsRepositoryMockRecorder {
	return m.recorder
}

// Counts mocks base method.
func (m *MockStatsRepository) Counts(ctx context.Context, streamID uuid.UUID) (int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Counts", ctx, streamID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Counts indicates an expected call of Counts.
func (mr *MockStatsRepositoryMockRecorder) Counts(ctx, streamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Counts", reflect.TypeOf((*MockStatsRepository)(nil).Counts), ctx, streamID)
}

// DeleteReaction mocks base method.
func (m *MockStatsRepository) DeleteReaction(ctx context.Context, streamID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReaction", ctx, streamID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteReaction indicates an expected call of DeleteReaction.
func (mr *MockStatsRepositoryMockRecorder) DeleteReaction(ctx, streamID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReaction", reflect.TypeOf((*MockStatsRepository)(nil).DeleteReaction), ctx, streamID, userID)
}

// GetReaction mocks base method.
func (m *MockStatsRepository) GetReaction(ctx context.Context, streamID, userID uuid.UUID) (*models.Reaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReaction", ctx, streamID, userID)
	ret0, _ := ret[0].(*models.Reaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReaction indicates an expected call of GetReaction.
func (mr *MockStatsRepositoryMockRecorder) GetReaction(ctx, streamID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReaction", reflect.TypeOf((*MockStatsRepository)(nil).GetReaction), ctx, streamID, userID)
}

// GetViews mocks base method.
func (m *MockStatsRepository) GetViews(ctx context.Context, streamID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetViews", ctx, streamID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetViews indicates an expected call of GetViews.
func (mr *MockStatsRepositoryMockRecorder) GetViews(ctx, streamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetViews", reflect.TypeOf((*MockStatsRepository)(nil).GetViews), ctx, streamID)
}

// IncrementViews mocks base method.
func (m *MockStatsRepository) IncrementViews(ctx context.Context, streamID uuid.UUID, now time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementViews", ctx, streamID, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementViews indicates an expected call of IncrementViews.
func (mr *MockStatsRepositoryMockRecorder) IncrementViews(ctx, streamID, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementViews", reflect.TypeOf((*MockStatsRepository)(nil).IncrementViews), ctx, streamID, now)
}

// UpsertReaction mocks base method.
func (m *MockStatsRepository) UpsertReaction(ctx context.Context, streamID, userID uuid.UUID, kind models.ReactionKind, now time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertReaction", ctx, streamID, userID, kind, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertReaction indicates an expected call of UpsertReaction.
func (mr *MockStatsRepositoryMockRecorder) UpsertReaction(ctx, streamID, userID, kind, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertReaction", reflect.TypeOf((*MockStatsRepository)(nil).UpsertReaction), ctx, streamID, userID, kind, now)
}
